language: node_js

node_js:
- '0.10'

before_script:
- npm install -g grunt-cli

script: ls -la

deploy:
  provider: heroku
  api_key:
    secure: BePDwofVlcb6hIZlgxyQFPYDtsx7JsCwmP3FyaCgJYm5sff0aJP+S6kvx5asO0VuIoIPk0XR13Keda5zPE4i1JG9Rud9PXCVoV/GPKjJ8puT4RBy7R03gHxf6uNWC6GfWIgi5sfxp0TY9GiyMy4q7iIOERbBSQV2uEonwGq1epc=
  app: young-wildwood-4158
  on:
    repo: jokeyrhyme/services.jokeyrhy.me

before_deploy:
- echo 'about to deploy ...'

after_deploy:
- echo '... deploy finished!'
